### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by antyhrabia** [zer0net/zerovoat#72] opened 2017-08-13 22:16 UTC
Hi,
I very like your work and ZeroVoat. After latest update we can't push new topics (we can only in [ZeroVoat clone](http://127.0.0.1:43110/1F85185qyK12LXYbWqqwPXywxALP9VRTGh/) who is ZeroVoat version with unchanges for some files, when creating topics worked).
For second, will you update content.json? I do some [investigation](http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/1RedkCkVaXuVXrqCMpoXQS29bwaqsuFdL/15NScazvsCHNmiXi6o6nvaMiwjeJYizgZQ/1501351469) and ZeroVoat hubs in Merger CDn have
```
 "optional": "(.*.epub|.*.jpg|.*.jpeg|.*.png|data/.*.gif|.*.avi|.*.ogg|.*.webm|.*.mp4|.*.mp3|.*.mkv|.*.eot|.*.svg|.*.woff|.*.woff2|.*.ttf|.*.zip|.*.nes|.*.bin|.*.sna|data/users)",
```
Which would changed to
```
 "optional": ".*.(epub|jpg|jpeg|png|data/gif|avi|ogg|webm|mp4|mp3|mkv|eot|svg|woff|woff2|ttf|zip|nes|bin|sna|data/users)",
```
Because of security [reasons](http://127.0.0.1:43110/Blog.ZeroNetwork.bit/?Post:114). But for some reason, this isn't repair situations. Quote from my comments
> Ok, not so fast happy eding for me xd: Putting image or video in topic or comment is not possible - problem with file signing ``Potentially unsafe part of the pattern: )* in ((?!json).)*$``. And as far I see it's only in my clone, so must be problem with my hub in my merger.
Update2.
Using your Zerovoat and their CDN hubs I can put image etc., but non in [my hub](127.0.0.1:43110/1GdYQgFtRAR9JymFP8VWSeJQzaSPJkZH2P/) :P I think it's problem somewhere in content.json, but I edit almost everything and still sukcs.
Edit3.
Okey, I found the problem. It's ``` "optional": "((?!json).)*$",``` in content.json in data/users folder in hub.
Edit4. xD
I deleted `*` but it showing me
```File not allowed: filename-jpg.jpg```
I tried delete all optional fraze from hub data/user/blablabla/content.json but it give me same communicat.

**Comment by dnelband** [comment] 2017-08-13 22:35
Hi, thanks for reporting.
the problem is fixed & ive changed the optional list as you recommended.

**Comment by antyhrabia** [comment] 2017-08-14 12:22
Fantastic, thanks! I will test it tomorrow. I have only small question:
Why you put "optional" to content.json ZeroVoat if you previously deleted it? If you use Merger CDN and his hubs, hubs use "optional" for files and I was thinking about changing optional in content.json from  "ZV Cluster 0".

**Comment by antyhrabia** [comment] 2017-08-14 13:44
Hmm, strange. I added new topic in udpated ZeroVoat, but it's invicible. I can see what I write in my data.json in personal folder. I can see and read and comment my new topic in ZeroVoat clone, but not in original ZeroVoat.
And there is still problem with
```
Content signing failed
Potentially unsafe part of the pattern: )* in ((?!json).)*$
```
It's appear when you want add media like jpg or mp4.

**Comment by antyhrabia** [comment] 2017-08-14 16:03
Okey, problem is in this 5 files from ZeroVoat:
```
app/controllers/channels.ctrl.js
app/controllers/main.ctrl.js
app/directives/files.directive.js
app/directives/moderations.directive.js
assets/lib/angular/angular.min.js
```
But I don't know how to fix this.

**Comment by dnelband** [comment] 2017-08-15 12:09
ok i found the problem, the content.json optional was not properly changed with the new rules. please test now, it would be fixed upon the upload function, unfortunately it would give the same error upon first upload, but nevertheless it should be fixed.

**Comment by antyhrabia** [comment] 2017-08-16 19:15
Okay, looks alright and working good. Loading new topic takes little time and sometimes it didn't appear at first moment on main all topics list, but if refresh page it appear and working good. That previous error communicat show as you say, on first posting, and on second and laters didn't appear. If you make new account it didn't show if you post first topic/comment and next etc.
I forked ZeroVoat and add your patched code to my clone to check code and as I see, you fixed it exellent. Fantastic job.
I allowed myself to make little change in my clone - I deleted optional line from content.json ZeroVoat, and instead, I changed line with optional to fixed version in my hub content.json in my forked merger, and it working same as your original your, so it's nice that it work.
However, I found an error. After entering "All channels" it is empty and at the bottom you can see the text with the number of hubs created (given the correct value) and the button to create a new channel.
And I have little technical question (maybe noob): You changes ```((?!json).)*$``` in app/controllers/main.ctrl.js to ```.*.(epub|jpg|jpeg|png|gif|avi|ogg|webm|mp4|mp3|mkv)```. This string ```((?!json).)*$``` is still in
```
app/controllers/channels.ctrl.js
app/directives/files.directive.js
app/directives/moderations.directive.js
```
As is everything working good now, so as I understand it's not nessesary to changed this on these 3 files, but I'm curious if there would be something better ors worse if changed that string in them?

**Comment by haschimoto** [comment] 2018-02-05 17:01
@dnelband : can be closed?

**Closed** 2018-02-06 11:29 UTC
Labels: ready
